[package]
name = "nvim-gmail"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
async-trait = "0.1.77"
nvim-rs = { version = "0.6.0", features = ["use_tokio"] }
rs-gmail = { version = "0.1.0", path = "../../rs-gmail" }
tokio = { version = "1.35.1", features = ["full"] }
